# Generated by Django 5.2.8 on 2025-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
    ]
