# Generated by Django 5.2.8 on 2025-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost Price of the product', max_digits=20),
            preserve_default=False,
        ),
    ]
