# Generated by Django 5.2.8 on 2025-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refunded_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost Price of the product from the supplier', max_digits=20),
        ),
    ]
