# Generated by Django 5.2.8 on 2025-12-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orderitem_refunded_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage tax, e.g7.5% VAT', max_digits=5),
        ),
    ]
